import time
import json
import random
import requests
from datetime import datetime

# ==========================================
# CONFIGURATION
# ==========================================
SOC_DASHBOARD_URL = "http://localhost:5000/api/predict"
# In a real enterprise, each branch has its own API key
AGENT_API_KEY = "school-a-key-999" 

# Mock Suricata alerts (Normally this script would tail /var/log/suricata/eve.json)
MOCK_ALERTS = [
    {"event_type": "alert", "src_ip": "185.22.14.102", "dest_ip": "10.0.0.5", "alert": {"signature": "ET WEB_SERVER Apache Log4j Attempt", "category": "Attempted Administrator Privilege Gain", "severity": 1}},
    {"event_type": "alert", "src_ip": "45.33.32.156", "dest_ip": "10.0.0.12", "alert": {"signature": "ET SCAN Nmap Scripting Engine", "category": "Web Application Attack", "severity": 2}},
    {"event_type": "alert", "src_ip": "112.85.42.13", "dest_ip": "10.0.0.8", "alert": {"signature": "ET POLICY SSH Brute Force Attempt", "category": "Misc activity", "severity": 2}},
]

def generate_sensor_payload():
    """Simulates the payload generated by an edge sensor (Wazuh/Suricata)."""
    base_alert = random.choice(MOCK_ALERTS)
    
    # Feature extraction exactly like parser.py
    features = [
        random.randint(40, 1000),  # duration
        random.choice([1, 2, 3]),  # protocol_type (tcp=1, udp=2, icmp=3)
        random.randint(1, 70),     # service
        random.choice([1, 2, 3, 4, 5]), # flag
        random.randint(0, 5000),   # src_bytes
        random.randint(0, 10000),  # dst_bytes
        random.choice([0, 1]),     # land
        random.randint(0, 5),      # wrong_fragment
        random.randint(0, 3),      # urgent
    ]
    # Pad to 41 features for ML model compatibility
    features.extend([0] * (41 - len(features)))

    return {
        "source_ip": base_alert["src_ip"],
        "destination_ip": base_alert["dest_ip"],
        "signature": base_alert["alert"]["signature"],
        "category": base_alert["alert"]["category"],
        "severity": base_alert["alert"]["severity"],
        "features": features,
        "type": "Suricata Alert"
    }

def run_agent():
    print(f"[*] Starting Remote Sensor Agent...")
    print(f"[*] Forwarding logs to: {SOC_DASHBOARD_URL}")
    print(f"[*] Authenticating with API Key: {AGENT_API_KEY}\n")
    
    headers = {
        "X-API-KEY": AGENT_API_KEY,
        "Content-Type": "application/json"
    }

    try:
        while True:
            payload = generate_sensor_payload()
            print(f"[{datetime.now().strftime('%H:%M:%S')}] 📡 Sending alert: {payload['signature']} from {payload['source_ip']}")
            
            try:
                response = requests.post(SOC_DASHBOARD_URL, json=payload, headers=headers, timeout=5)
                if response.status_code == 200:
                    data = response.json()
                    print(f"   ✅ Received by SOC. ML Prediction: {data.get('prediction')} ({data.get('severity')})")
                else:
                    print(f"   ❌ Rejected by SOC (HTTP {response.status_code})")
            except requests.exceptions.RequestException as e:
                print(f"   ⚠️ Connection failed: {e}")
                
            # Random delay to simulate real organic traffic
            time.sleep(random.uniform(2.0, 7.0))
            
    except KeyboardInterrupt:
        print("\n[*] Agent shutting down.")

if __name__ == "__main__":
    run_agent()
