import sqlite3
import os

DB_NAME = "alerts.db"

def get_connection():
    # Use absolute path for DB to avoid issues with different CWDs
    db_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), DB_NAME)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn

def insert_alert(alert):
    conn = get_connection()
    cursor = conn.cursor()

    try:
        # Insert into alerts table
        cursor.execute("""
            INSERT INTO alerts (
                timestamp,
                src_ip,
                dest_ip,
                signature,
                category,
                severity,
                ml_prediction,
                confidence,
                cve,
                cvss,
                behavior,
                country,
                city,
                latitude,
                longitude,
                org_name,
                mitre_id,
                mitre_tactic,
                recommendation,
                status,
                analyst_notes,
                incident_id,
                assigned_analyst
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            alert["timestamp"],
            alert["src_ip"],
            alert["dest_ip"],
            alert["signature"],
            alert["category"],
            alert["severity"],
            alert["ml_prediction"],
            alert["confidence"],
            alert.get("cve", "N/A"),
            alert.get("cvss", 0.0),
            alert.get("behavior", "N/A"),
            alert.get("country", "Unknown"),
            alert.get("city", "Unknown"),
            alert.get("latitude", 0.0),
            alert.get("longitude", 0.0),
            alert.get("org_name", "Local Sensor"),
            alert.get("mitre_id", "N/A"),
            alert.get("mitre_tactic", "N/A"),
            alert.get("recommendation", "N/A"),
            "NEW",
            "",
            "N/A", # temp incident_id
            "Unassigned"
        ))
        
        alert_id = cursor.lastrowid
        
        # Incident Engine Correlation Logic
        # Check if an open incident exists for this IP and Signature
        title = f"{alert['signature']} Campaign"
        cursor.execute('''
            SELECT incident_id FROM incidents 
            WHERE src_ip = ? AND title = ? AND status != 'RESOLVED' AND status != 'FALSE_POSITIVE'
        ''', (alert['src_ip'], title))
        
        existing_incident = cursor.fetchone()
        
        if existing_incident:
            incident_id = existing_incident[0]
            # Update existing incident
            cursor.execute('''
                UPDATE incidents 
                SET alert_count = alert_count + 1, updated_at = ?
                WHERE incident_id = ?
            ''', (alert['timestamp'], incident_id))
        else:
            # Create new incident
            incident_id = f"INC-2026-{alert_id:04d}"
            cursor.execute('''
                INSERT INTO incidents (
                    incident_id, title, severity, status, assigned_analyst, 
                    analyst_notes, src_ip, org_name, alert_count, created_at, 
                    updated_at, mitre_id, mitre_tactic, recommendation
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?)
            ''', (
                incident_id, title, alert['severity'], "NEW", "Unassigned",
                "", alert['src_ip'], alert.get("org_name", "Local Sensor"),
                alert['timestamp'], alert['timestamp'], alert.get("mitre_id", "N/A"),
                alert.get("mitre_tactic", "N/A"), alert.get("recommendation", "N/A")
            ))
            
            # Auto-generate chronological timeline log
            cursor.execute('''
                INSERT INTO incident_logs (incident_id, timestamp, action_type, user, details)
                VALUES (?, ?, ?, ?, ?)
            ''', (incident_id, alert['timestamp'], "CREATION", "System", "Incident automatically generated by SOC Engine."))
            
        # Update the alert with the final incident_id
        cursor.execute("UPDATE alerts SET incident_id = ? WHERE id = ?", (incident_id, alert_id))

        # Also update attackers table for historical intelligence
        cursor.execute("""
            INSERT INTO attackers (ip_address, country, city, latitude, longitude, total_hits, last_seen)
            VALUES (?, ?, ?, ?, ?, 1, ?)
            ON CONFLICT(ip_address) DO UPDATE SET
            total_hits = total_hits + 1,
            last_seen = ?
        """, (
            alert["src_ip"], 
            alert.get("country", "Unknown"),
            alert.get("city", "Unknown"),
            alert.get("latitude", 0.0),
            alert.get("longitude", 0.0),
            alert["timestamp"], 
            alert["timestamp"]
        ))

        # SOAR Playbook: Automated Response Actions
        if alert['severity'] == 'Critical':
            import datetime
            now = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
            
            # 1. Auto-Escalate Incident
            cursor.execute('''
                UPDATE incidents 
                SET status = 'ESCALATED', assigned_analyst = 'SOC Lead', updated_at = ?
                WHERE incident_id = ? AND status = 'NEW'
            ''', (now, incident_id))
            
            if cursor.rowcount > 0:
                cursor.execute('''
                    INSERT INTO incident_logs (incident_id, timestamp, action_type, user, details)
                    VALUES (?, ?, ?, ?, ?)
                ''', (incident_id, now, "STATUS_CHANGE", "SOAR Engine", "Auto-escalated Critical Incident"))
                cursor.execute('''
                    INSERT INTO incident_logs (incident_id, timestamp, action_type, user, details)
                    VALUES (?, ?, ?, ?, ?)
                ''', (incident_id, now, "ASSIGNMENT", "SOAR Engine", "Auto-assigned to SOC Lead"))

            # 2. Auto-Block IP
            try:
                cursor.execute('''
                    INSERT INTO firewall_rules (ip_address, reason, org_name, timestamp)
                    VALUES (?, ?, ?, ?)
                ''', (alert['src_ip'], f"SOAR Block: {alert['signature']}", alert.get('org_name', 'All'), now))
                
                cursor.execute('''
                    INSERT INTO incident_logs (incident_id, timestamp, action_type, user, details)
                    VALUES (?, ?, ?, ?, ?)
                ''', (incident_id, now, "MITIGATION", "SOAR Engine", f"Auto-blocked IP {alert['src_ip']} at Edge Firewall"))
                
                # 3. Send Telegram Alert
                try:
                    import sys
                    import os
                    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                    from alert_bot import AlertBot
                    bot = AlertBot()
                    bot.send_alert(f"SOAR Auto-Mitigation Triggered!\nCritical threat from {alert['src_ip']} ({alert['signature']}).\nIP Blocked and Escalated to SOC Lead.")
                except Exception as bot_e:
                    print(f"Failed to send SOAR bot alert: {bot_e}")
                    
            except sqlite3.IntegrityError:
                # IP already blocked
                pass

        conn.commit()
        
        # Phase 13: Real-Time Event Synchronization
        # Fire internal webhook to Flask app to broadcast WebSocket event
        import requests
        try:
            requests.post(
                'http://127.0.0.1:5000/api/internal/notify', 
                json={'type': 'new_alert', 'incident_id': incident_id, 'alert_id': alert_id},
                timeout=0.5
            )
        except:
            pass # Ignore if Flask is not running or timeout
            
    except Exception as e:
        print(f"Error inserting alert: {e}")
        conn.rollback()
    finally:
        conn.close()

def get_recent_alerts(limit=100, org_name=None):
    conn = get_connection()
    if org_name and org_name != 'All':
        alerts = conn.execute("""
            SELECT * FROM alerts WHERE org_name = ? ORDER BY id DESC LIMIT ?
        """, (org_name, limit)).fetchall()
    else:
        alerts = conn.execute("""
            SELECT * FROM alerts ORDER BY id DESC LIMIT ?
        """, (limit,)).fetchall()
    conn.close()
    return [dict(a) for a in alerts]

def get_recent_incidents(limit=50, org_name=None):
    conn = get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    if org_name and org_name != 'All':
        cursor.execute('''
            SELECT * FROM incidents WHERE org_name = ? ORDER BY created_at DESC LIMIT ?
        ''', (org_name, limit))
    else:
        cursor.execute('''
            SELECT * FROM incidents ORDER BY created_at DESC LIMIT ?
        ''', (limit,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]
